### ISSUE TITLE
GCAN02 Crash

### ISSUE THREAD

**Issue by RaikouSRL** [uzuhenry/DigimonWorldUSEnemyRandomizer#1]
https://clips.twitch.tv/FamousHorribleDugongTwitchRPG-cyi2ErlaphzVNkpt

Was testing the randomizer on stream, exited the elevator after Ogre 2 and it hardlocked on the loading screen

SEED: 1480560936 w Basic Setting, was using Meek+Syd Rando with it

**Comment by uzuhenry** [comment]
It was a faulty offset mapping, thx a lot for the help! 

You can find the most up to date data files in the repository.
